### ISSUE TITLE
Migrate to Scalaz 7.1

### ISSUE THREAD

**Issue by LeifW** [pelotom/effectful#11]
Scalaz 7.1 is the current version, and is used in most projects I work on. Notably, the multibot in the #scala IRC channel is on 7.1, and we'd need to have a compatible effectful version for it to be included in there.

**Comment by pelotom** [comment]
Hopefully that does the trick. LMK if you add it to the bot, I'd love to try it out.

**Comment by LeifW** [comment]
You can try it out in on multibot in #scala or wherever, now!
https://github.com/OlegYch/multibot/pull/3
